Blog app - add forms
78fatemanazari/Interacti_Blog pull request #10
Opened 2023-11-30 20:35 UTC by 78fatemanazari

### Project requirements
- Create a method called current_user in your ApplicationController to make current user data available to all controllers.
It will return the first user from the database.
Don't worry about proper authentication at this time. You will add it in the upcoming projects.
- Create forms to perform the following functions:
- Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
- Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
- Allow Users to add likes to Posts.

2023-11-30 21:03 UTC, V-Blaze requested changes
## Hi @78fatemanazari 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![giphy](https://user-images.githubusercontent.com/107632780/229314554-3700de13-2c00-46d5-bc77-46ad09af7467.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Created all the required controller actions ✔
-  Added routes correctly 👋 
-  Correct git flow✔

 ## Required Changes ♻️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-30 21:03 UTC, V-Blaze commented on app/controllers/posts_controller.rb
> +    end
- You have done great so far :+1: But there are a few requirements you still need to meet before moving to the next milestone. :+1: :100: 

- [ ] While creating a new post and I click on the submit button, even though the post seems to be created, this error got returned to be in the console and on the browser. The error seems to be referring to your view files, I'll suggest you fix this. :+1: :100: 

- - Screenshot reference:
![Screenshot from 2023-11-30 21-50-46](https://github.com/78fatemanazari/Interacti_Blog/assets/107632780/2cc99ddc-c5fd-4f48-b650-8e17a623cbfa)

2023-11-30 21:03 UTC, V-Blaze commented on app/controllers/posts_controller.rb
>    end
- [ ] When I click on a post in order to go to the `post show page` I get this error in the browser, I suggest you also fix this. :+1: :100: 

- - Screenshot reference:
![Screenshot from 2023-11-30 21-51-47](https://github.com/78fatemanazari/Interacti_Blog/assets/107632780/f58d7908-1606-4ac8-bcfe-9eb039a2305c)

2023-11-30 21:03 UTC, V-Blaze commented on app/controllers/comments_controller.rb
> +  end
- - Requirement screenshot:
![Selection_051](https://github.com/78fatemanazari/Interacti_Blog/assets/107632780/9a5df00b-0a37-4f16-be7b-37803c65abc5)


- [ ] According to the project requirement, the comment should be created onbehalf of the `current user` which you get by calling the `current_user` method you created. currently, you are getting the user by the ID passed from the request, although this works, that's not what was required. I suggest you stick to the requirement and use the `current_user` method here. :smile: :wave:

2023-12-01 16:33 UTC, OyePriscilla approved these changes
Hi @78fatemanazari 👏 👏 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Assigned the `current_user` to the user attribute of a `Comment` instance. ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-01 17:42 UTC, merged